[185517739] Introducing automatic PR action
alphagov/paas-s3-broker-boshrelease pull request #20
Opened 2023-09-21 16:55 UTC by dark5un

This PR introduce automated PR creation with the use of GitHub actions upon [bosh golang package](https://github.com/cloudfoundry/bosh-package-golang-release) updates.

2023-09-22 09:00 UTC, AP-Hunt requested changes

2023-09-22 09:00 UTC, AP-Hunt commented on .github/workflows/generate_golang_bump_pr.yml
> +          cat <<-EOF > "$TEMPLATE_VENDOR_PACKAGING_CONFIGURATION"
Let's extract this so we can get linters and stuff against it

2023-09-22 09:00 UTC, AP-Hunt commented on .github/workflows/generate_golang_bump_pr.yml
> +        run: |
GitHub Actions has [conditional jobs](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution) that you can use instead of an `if` in the script

2023-09-22 16:08 UTC, dark5un commented on .github/workflows/generate_golang_bump_pr.yml
> +        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
👍  using v4 now (remind me to change this on pass-cf as well)

2023-09-22 16:09 UTC, dark5un commented on .github/workflows/generate_golang_bump_pr.yml
> +          cat <<-EOF > "$TEMPLATE_VENDOR_PACKAGING_CONFIGURATION"
👍 All things moved in a shell lib file

2023-09-22 16:10 UTC, dark5un commented on .github/workflows/generate_golang_bump_pr.yml
> +        run: |
👍 All things moved in a shell lib file. It has become a matter of three functions now.

2023-09-25 13:58 UTC, AP-Hunt commented on .github/workflows/generate_golang_bump_pr.yml
> +          if [ $(do_vendor_packaging) = 1 ]; then
We should output something explaining why we didn't take action, so it can't be mistaken for something simply failing

2023-09-25 13:59 UTC, AP-Hunt approved these changes

2023-09-25 14:07 UTC, dark5un commented on .github/workflows/generate_golang_bump_pr.yml
> +          if [ $(do_vendor_packaging) = 1 ]; then
👍

2023-09-25 14:50 UTC, merged